terraform {
  required_version = ">= 1.11"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }

  # Bucket, region and locking come from infra/backend.hcl, generated by bootstrap.sh:
  #   terraform init -backend-config=../backend.hcl
  backend "s3" {
    key = "platform/terraform.tfstate"
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      Project   = var.project
      Layer     = "platform"
      ManagedBy = "terraform"
    }
  }
}
