#!/usr/bin/env bash
# Creates the Terraform state bucket. Run once, by a human, with admin credentials.
#
# This is the only script that needs long-lived AWS keys. Everything after it authenticates
# through GitHub OIDC, which is why this layer is deliberately small and separate.
#
#   PROJECT=rag AWS_REGION=us-east-1 bash pipelines/scripts/bootstrap.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BOOTSTRAP_DIR="$REPO_ROOT/infra/bootstrap"
BACKEND_FILE="$REPO_ROOT/infra/backend.hcl"

PROJECT="${PROJECT:-rag}"
REGION="${AWS_REGION:-us-east-1}"
BUDGET_LIMIT="${BUDGET_LIMIT:-20}"
ASSUME_YES="${ASSUME_YES:-false}"

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

command -v aws >/dev/null 2>&1 || die "aws CLI not found — see README section 4"
command -v terraform >/dev/null 2>&1 || die "terraform not found — see README section 4"

account_id="$(aws sts get-caller-identity --query Account --output text 2>/dev/null)" \
  || die "no usable AWS credentials. Run 'aws configure' or export AWS_PROFILE."
caller_arn="$(aws sts get-caller-identity --query Arn --output text)"

# Asked for rather than defaulted: a budget alert nobody receives is not a guardrail.
# Prompting only works with a terminal attached, so a non-interactive run must supply the value
# rather than silently skip the prompt.
BUDGET_EMAIL="${BUDGET_EMAIL:-}"
if [ -z "$BUDGET_EMAIL" ]; then
  [ -t 0 ] || die "no terminal attached — set BUDGET_EMAIL=you@example.com and re-run"
  read -r -p "Email address for budget alerts: " BUDGET_EMAIL
fi
[ -n "$BUDGET_EMAIL" ] || die "a budget alert email is required"

cat <<EOF

Bootstrap — creates the Terraform state bucket and the account cost budget.

  account      : $account_id
  identity     : $caller_arn
  region       : $REGION
  bucket       : ${PROJECT}-tfstate-${account_id}
  budget       : \$${BUDGET_LIMIT}/month -> $BUDGET_EMAIL

EOF

# Applying to the wrong account is the expensive mistake here, so the account is shown and
# confirmed rather than assumed from whatever profile happened to be exported.
if [ "$ASSUME_YES" != "true" ]; then
  [ -t 0 ] || die "no terminal attached — set ASSUME_YES=true to skip confirmation, or run interactively"
  read -r -p "Create state infrastructure in account ${account_id}? [y/N] " reply
  case "$reply" in
    y | Y) ;;
    *) die "aborted" ;;
  esac
fi

terraform -chdir="$BOOTSTRAP_DIR" init -input=false
terraform -chdir="$BOOTSTRAP_DIR" apply -input=false -auto-approve \
  -var "project=$PROJECT" \
  -var "region=$REGION" \
  -var "budget_limit_usd=$BUDGET_LIMIT" \
  -var "budget_notification_email=$BUDGET_EMAIL"

bucket="$(terraform -chdir="$BOOTSTRAP_DIR" output -raw state_bucket)"

# Written rather than committed: it carries the account id, and every other layer reads it as
# partial backend config so the bucket name is never copied by hand into a second place.
cat > "$BACKEND_FILE" <<EOF
# Generated by pipelines/scripts/bootstrap.sh — do not edit, do not commit.
bucket       = "$bucket"
region       = "$REGION"
encrypt      = true
use_lockfile = true
EOF

cat <<EOF

Done.

  state bucket : $bucket
  backend cfg  : infra/backend.hcl  (gitignored — regenerate with this script on a fresh clone)
  budget       : \$${BUDGET_LIMIT}/month, alerts to $BUDGET_EMAIL

Confirm the budget subscription email that AWS sends you, or the alerts go nowhere.

Next:
  1. Enable Bedrock model access in $REGION for:
       amazon.titan-embed-text-v2:0
       anthropic.claude-3-5-haiku-20241022-v1:0
  2. bash pipelines/scripts/platform.sh     # GitHub OIDC provider, pipeline roles, ECR
EOF
